---
- name: "Copying Settings Files"
  copy:
    src: "{{ playbook_dir }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying bash_aliases"
  copy:
    src: "{{ playbook_dir }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying bashrc"
  copy:
    src: "{{ playbook_dir }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying scripts files"
  copy:
    src: "{{ playbook_dir }}/scripts/"
    dest: "{{ ansible_env.HOME }}/bin/"
    mode: 0775
- name: "Setting Mate Desktop"
  shell:
    cmd: "dconf load /org/mate/ < {{ playbook_dir }}/files/mate.settings"

- name: "Checking if sudo was setting"
  lineinfile: 
    path: /etc/sudoers
    line: "{{ ansible_env.USER }} ALL=(ALL) NOPASSWD:ALL"
    state: present
  become: true
  become_method: sudo

