---
- name: "Copying Settings Files"
  copy:
    src: "{{ playbook_dir }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying bash_aliases"
  copy:
    src: "{{ playbook_dir }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying bashrc"
  copy:
    src: "{{ playbook_dir }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying scripts files"
  copy:
    src: "{{ playbook_dir }}/scripts/"
    dest: "{{ ansible_env.HOME }}/bin/"
    mode: 0775
- name: "Installing Feroxbuster"
  git:
     clone: true
     dest: "/opt/feroxbuster/"
     repo: "https://github.com/epi052/feroxbuster.git"
- name: "Downloading Fonts"
  get_url: 
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hack.zip
    dest: "/tmp/Hack.zip"

- name: "Creating fonts folder"
  file:
    path: "{{ansible_env.HOME}}/.local/share/fonts"
    state: "directory"
    mode: 0777

- name: "Uncompress Fonts Zip File"
  shell: |
    cd {{ansible_env.HOME}}/.local/share/fonts/ && unzip -o /tmp/Hack.zip
#- name: "Installing Software"
#  apt:
#    name: "git, tmux, python-dev"
#    when: "find('git') != -1"
#  become: true
#  become_method: sudo