---
- name: "Checking if sudo was setting"
  lineinfile: 
    path: /etc/sudoers
    line: "{{ ansible_env.USER }} ALL=(ALL) NOPASSWD:ALL"
    state: present
  become: true
  become_method: sudo

- name: "Copying Settings Files"
  copy:
    src: "{{ playbook_dir }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying bash_aliases"
  copy:
    src: "{{ playbook_dir }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying bashrc"
  copy:
    src: "{{ playbook_dir }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}/"

- name: "Creating vimrc"
  copy:
    dest: "{{ ansible_env.HOME}}/.vimrc"
    content: |
      set number
      syntax on

- name: "Copying scripts files"
  copy:
    src: "{{ playbook_dir }}/scripts/"
    dest: "{{ ansible_env.HOME }}/bin/"
    mode: 0775

- name: "Checking if dconf exists"
  stat:
    path: "/usr/bin/dconf"
  register: dconf_command
  become: true
  become_method: sudo

- name: "Setting Mate Desktop"
  shell:
    cmd: "dconf load /org/mate/ < {{ playbook_dir }}/files/mate.settings"
  when: dconf_command.stat.exists

- name: "Copying icons"
  copy:
    src: "{{ playbook_dir }}/files/utilities-terminal.svg"
    dest: "{{ ansible_env.HOME }}/Pictures/"

- name: "Copying Terminal icons"
  copy:
    src: "{{ playbook_dir }}/files/utilities-terminal.svg"
    dest: "/usr/share/icons/hackthebox/22/apps/utilities-terminal.svg"
  become: true
  become_method: sudo

- name: "Copying Terminal icons"
  copy:
    src: "{{ playbook_dir }}/files/utilities-terminal.svg"
    dest: "/usr/share/icons/hackthebox/32/apps/"
  become: true
  become_method: sudo

- name: "Copying Terminal icons"
  copy:
    src: "{{ playbook_dir }}/files/utilities-terminal.svg"
    dest: "/usr/share/icons/hackthebox/64/apps/"
  become: true
  become_method: sudo

- name: "Copying Terminal icons"
  copy:
    src: "{{ playbook_dir }}/files/utilities-terminal.svg"
    dest: "/usr/share/icons/hackthebox/24x24/apps/"
  become: true
  become_method: sudo

- name: "Copying Mate Settings Desktop"
  copy:
    dest: "/usr/share/applications/mate-terminal.desktop"
    content: |
      #!/usr/bin/env xdg-open
      [Desktop Entry]
      Version=1.0
      Type=Application
      Terminal=false
      Icon={{ ansible_env.HOME}}/Pictures/utilities-terminal.svg
      Icon[en_US]={{ ansible_env.HOME }}/Pictures/utilities-terminal.svg
      Name[en_US]=mate-terminal
      Exec=/usr/bin/mate-terminal
      Name=mate-terminal
  become: true
  become_method: sudo