---
- name: "Copying Settings Files"
  copy:
    src: "{{ playbook_dir }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying bash_aliases"
  copy:
    src: "{{ playbook_dir }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying bashrc"
  copy:
    src: "{{ playbook_dir }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}/"
- name: "Copying scripts files"
  copy:
    src: "{{ playbook_dir }}/scripts/"
    dest: "{{ ansible_env.HOME }}/bin/"
    mode: 0775
- name: "Creating Shortcuts Keybinding"
  shell:
    cmd: "dconf load /org/mate/desktop/keybindings/ < {{ playbook_dir }}/files/custom-keybindings"

- name: "Setting SUDO for {{ansible_env.USER}}"
  shell:
    cmd: echo "{{ansible_env.USER}} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  become: true
  become_method: sudo
    
#- name: "Installing Software"
#  apt:
#    name: "git, tmux, python-dev"
#    when: "find('git') != -1"
#  become: true
#  become_method: sudo