---
# tasks file for rules/bspwn-desktop
- name: "Creating polybar folder"
  file:
    path: "{{ansible_env.HOME}}/.config/polybar"
    state: directory

- name: "Install bspwm sxhkd"
  apt:
    name: bspwm,sxhkd, polybar
    update_cache: true
    state: present
  become: true
  become_method: sudo

- name: "Copy bspwn files"
  copy:
    src: "{{role_path}}/files/bspwmrc" 
    dest: "{{ansible_env.HOME}}/.config/bspwmrc"
    mode: "preserve"
  
- name: "Copy sxhkd files"
  copy:
    src: "{{role_path}}/files/sxhkdrc" 
    dest: "{{ansible_env.HOME}}/.config/sxhkdrc"
    mode: "preserve"

- name: "Copy polybar files"
  copy:
    src: "{{role_path}}/files/polybar/{{item}}"
    dest: "{{ansible_env.HOME}}/.config/polybar/{{item}}"
    mode: "preserve"
  loop:
    - config
    - get_window_titles.sh
    - launch.sh
    - select_window.sh
