---
- name: "Checinkg sublimetext"
  stat:
    path: "/usr/bin/subl"
  register: subl_command

- name: "Configuring Subl Repos"
  shell: |
    wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null
    echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
  when: not subl_command.stat.exists

- name: "Change opt permissions"
  shell:
    cmd: chown -R {{ ansible_env.USER}}:{{ ansible_env.USER}} /opt
  become: true
  become_method: sudo

- name: "Install xclip,sublime-text, build-essential,dkms,linux-headers-{{ansible_kernel}},rofi, git,apt-transport-https, vim, grc, tmux, python3-pip, libssl-dev, libffi-dev, python-dev-is-python3, python3-venv, ssh, jq"
  apt:
    name: "{{item}}"
    state: present
  loop:
    - xclip
    - sublime-text
    - build-essential
    - dkms
    - linux-headers-{{ansible_kernel}}
    - rofi
    - git
    - apt-transport-https
    - vim
    - grc
    - tmux
    - python3-pip
    - libssl-dev
    - libffi-dev
    - python-dev-is-python3
    - python3-venv
    - ssh
    - jq
    - pipx
  become: true
  become_method: sudo

#- name: "Checinkg VsCode"
#  stat:
#    path: "/usr/bin/codium"
#  register: code_command

- name: "Installing pip tools"
  pip:
    name: updog, pipx, impacket

- name: "Checking 24x24 theme folder"
  stat:
    path: "/usr/share/icons/hackthebox/24x24/apps"
  register: icons_24_folder

- name: "Creating 24 icons folder"
  file:
    path: "/usr/share/icons/hackthebox/24x24/apps"
    state: "directory"
    mode: 0755
  become: true
  become_method: sudo
  when: not icons_24_folder.stat.exists
