---
- name: "Installing Pentest from deb repositories"
  apt:
    name: whatweb,nmap,golang
  become: true
  become_method: sudo

- name: "Checking FFUF"
  stat:
    path: "/opt/ffuf/"
  register: ffuf_folder

- name: "Cloning FFUF"
  git:
    repo: "https://github.com/ffuf/ffuf"
    dest: "/opt/ffuf"
    update: true
  register: compile_ffuf
  when: not ffuf_folder.stat.exists

- name: "Compiling FFUF"
  shell: |
    cd /opt/ffuf
    go get
    go build
  when: compile_ffuf.changed

- name: "Creating Symbolic Link"
  file:
    src: "/opt/ffuf/ffuf"
    dest: "/usr/bin/ffuf"
    state: link
  when: compile_ffuf.changed
  become: true
  become_method: sudo

- name: "Checking sqlmap"
  stat:
    path: "/opt/sqlmap/"
  register: sqlmap_folder

- name: "Cloning SqlMap"
  git:
    repo: "https://github.com/sqlmapproject/sqlmap.git"
    dest: "/opt/sqlmap"
    update: true
  when: not sqlmap_folder.stat.exists

- name: "Checking WordLists folder exists"
  stat:
    path: "/opt/wordlists"
  register: WordLists_folder

- name: "Creating folder"
  shell: mkdir /opt/wordlists
  become: true
  become_method: sudo
  when: not WordLists_folder.stat.exists

- name: "Cloning WordLists Repositories"
  git:
    repo: "{{item.origin}}"
    dest: "/opt/wordlists/{{item.dest}}"
    update: true

  loop:
    - {"origin":"https://github.com/insidetrust/statistically-likely-usernames.git","dest":"statistically-likely-usernames"}
    - {"origin":"https://github.com/danielmiessler/SecLists.git","dest":"SecLists"}
    - {"origin":"https://github.com/daniel2005d/WordLists.git","dest":"WordLists"}

  when: WordLists_folder.stat.exists == true
  become: true
  become_method: sudo

- name: "Checking Crackmapexec"
  stat:
    path: "/opt/CrackMapExec"
  register: crackmapexec_folder

- name: "Cloning Crackmapexec"
  git:
    repo: "https://github.com/Porchetta-Industries/CrackMapExec"
    dest: "/opt/CrackMapExec"
    update: true
  when: not crackmapexec_folder.stat.exists

- name: "Installing CrackMapExec"
  shell: |
    cd /opt/CrackMapExec
    pipx install .
  when: not crackmapexec_folder.stat.exists

- name: "Checking sqlmap command"
  stat:
    path: "/usr/bin/sqlmap"
  register: sqlmap_command

- name: "Creating link to sqlmap"
  shell:
    cmd: ln -s /opt/sqlmap/sqlmap.py /usr/bin/sqlmap
  become: true
  become_method: sudo
  when: not sqlmap_command.stat.exists
