---
- name: "Installing Pentest from deb repositories"
  apt:
    name: whatweb
  become: true
  become_method: sudo

- name: "Checking FFUF"
  stat:
    path: "/opt/ffuf/"
  register: ffuf_folder

- name: "Cloning FFUF"
  git:
    repo: "https://github.com/ffuf/ffuf"
    dest: "/opt/ffuf"
    update: true
  register: compile_ffuf
  when: not ffuf_folder.stat.exists

- name: "Compiling FFUF"
  shell: |
    cd /opt/ffuf
    go get
    go build
  when: compile_ffuf.changed

- name: "Checking sqlmap"
  stat:
    path: "/opt/sqlmap/"
  register: sqlmap_folder

- name: "Cloning SqlMap"
  git:
    repo: "https://github.com/sqlmapproject/sqlmap.git"
    dest: "/opt/sqlmap"
    update: true
  when: not sqlmap_folder.stat.exists

- name: "Checking SecLists"
  stat:
    path: "/opt/SecLists"
  register: SecLists_folder

- name: "Cloning SecLists"
  git:
    repo: "https://github.com/danielmiessler/SecLists.git"
    dest: "/opt/SecLists"
    update: true
  when: not SecLists_folder.stat.exists

- name: "Checking Feroxbuster"
  stat:
    path: "/opt/feroxbuster/"
  register: ferobuster_folder

- name: "Checking Crackmapexec"
  stat:
    path: "/opt/CrackMapExec"
  register: crackmapexec_folder

- name: "Cloning Crackmapexec"
  git:
    repo: "https://github.com/Porchetta-Industries/CrackMapExec"
    dest: "/opt/CrackMapExec"
    update: true
  when: not crackmapexec_folder.stat.exists
    
- name: "Installing CrackMapExec"
  shell: |
    cd /opt/CrackMapExec
    pipx install .
  when: not crackmapexec_folder.stat.exists


- name: "Installing Feroxbuster"
  git:
     clone: true
     dest: "/opt/feroxbuster/"
     repo: "https://github.com/epi052/feroxbuster.git"
  when: not ferobuster_folder.stat.exists

- name: "Checking sqlmap command"
  stat:
    path: "/usr/bin/sqlmap"
  register: sqlmap_command

- name: "Creating link to sqlmap"
  shell:
    cmd: ln -s /opt/sqlmap/sqlmap.py /usr/bin/sqlmap
  become: true
  become_method: sudo
  when: not sqlmap_command.stat.exists  
