---
- name: "Checinkg firefox"
  stat:
    path: "/usr/share/firefox/distribution"
  register: firefox_esr

- name: "Updating firefox policies"
  template: 
    src: "templates/firefox-policies.json.j2"
    dest: "/usr/share/firefox/distribution/policies.json"
  become: true
  become_method: sudo
  when: firefox_esr.stat.exists

- name: "Updating ESR firefox"
  template: 
    src: "templates/firefox-policies.json.j2"
    dest: "/usr/share/firefox-esr/distribution/policies.json"
  become: true
  become_method: sudo